modLoader="javafml"
loaderVersion="${loader_version}"
issueTrackerURL="https://github.com/mekanism/Mekanism/issues"
license="MIT"

[[mods]]
    modId="mekanismtools"
    version="${file.jarVersion}"
    displayName="Mekanism: Tools"
    displayURL="https://aidancbrady.com/mekanism/"
    authors="Aidancbrady, Thommy101, Thiakil, pupnewfster, dizzyd"
    credits="unpairedbracket, CyanideX, Ridanisaurus and many others"
    logoFile="logo.png"
    description='''Tools module for Mekanism'''

[[dependencies.mekanismtools]]
    modId="mekanism"
    type="required"
    versionRange="[${file.jarVersion}]"
    ordering="AFTER"
    side="BOTH"